name = "Ansible Lint"
description = "Run ansible-lint on playbooks, roles and collections."
category = "language"
visibility = "public"

[analyzer]
  command = "python /app/main.py"

[build]
  image = "cytopia/ansible-lint:5"
  steps = "cp -r . /app"
