title = "Tasks that run when changed should likely be handlers"
severity = "minor"
category = "bug-risk"
description = """
If a task has a `when: result.changed` setting, it is effectively acting as a
handler.

In the below example, the second task notifies the handler to restart `apache`.

```yml
---
- name: Verify apache installation
  hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: Write the apache config file
    ansible.builtin.template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf
    notify:
    - Restart apache

  - name: Ensure apache is running
    ansible.builtin.service:
      name: httpd
      state: started

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted

```

For more details, do checkout the documentation
[here](https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html).
"""
