title = "Shells that use pipes should set the `pipefail` option"
severity = "minor"
category = "bug-risk"
description = """
Without the pipefail option set, a shell command that implements a pipeline can
fail and still return 0.

If any part of the pipeline other than the terminal command fails, the whole pipeline will still return 0, which may be considered a success by Ansible. Pipefail is available in the bash shell.

For example :

It is recommended to use `pipefail` with `shell` command that uses pipes like this :

```yml
- name: Example task
 shell: set -o pipefail && ls -ld /tmp | tr -d tmp
 args:
   executable: /usr/bin/bash
```

instead of using just the bare command :

```yml
- name: Example task
 shell: ls -ld /tmp | tr -d tmp
 args:
   executable: /usr/bin/bash
```
"""
