title = "Should not use `command` instead of arguments to modules"
severity = "major"
category = "antipattern"
description = """
Executing a command when there are arguments to modules is not recommended.

Using `command` module is a bad idea, since it’s not idempotent in nature, the
developer is responsible for handling the idempotency of the task.

Example :

Instead of using `command` as used in the below snippet :

```yml
- name: restart nginx
  command: sudo systemctl restart nginx
```

It is better and recommended to use a `service` module with KV arguments. Like :

```yml
- name: restart nginx
  service:
    name: nginx
    state: restarted
```
"""
