title = "`become_user` requires `become` to work as expected"
severity = "major"
category = "bug-risk"
description = """

`become_user` without `become: yes` will not actually change user.

When `become` is set to `yes` but `become_user` is not set, user `root` is set.

## Example

### Bad practice

```yml
- name: Run a command as the apache user
  command: somecommand
  become_user: apache
```

### Recommended

```yml
- name: Run a command as the apache user
  command: somecommand
  become: yes
  become_user: apache
```
"""

weight = 80