title = "Replace `local_action` with `delegate_to: localhost`"
severity = "minor"
category = "style"
description = """
`local_action` is equivalent to `delegate_to: localhost` in terms of functionality, but it is not very readable, and does not match the style of typical Ansible tasks.
"""

weight = 40