title = "`become_user` requires `become` to work as expected"
severity = "major"
category = "antipattern"
description = """
`become_user` without `become` will not actually change user.

For example, in the example below the command will be run with `apache` as the
user :

```yml
- name: Run a command as the apache user
  command: somecommand
  become: true
  become_user: apache
```

The default value of `become_user` is `root` when not specifically set.
"""
